### ISSUE TITLE
window object is not accessible while using sdk on server

### ISSUE THREAD

**Issue by athulanilthomas** [spotify/spotify-web-api-ts-sdk#108]
### Environment
- Processor: 11th Gen Intel® Core™ i7-1165G7 @ 2.80GHz × 8
- OS Name: Ubuntu 22.04.4 LTS
- Memory: 16.0 GiB
- Node Version: v20.11.0
- Nuxt Version: 3.9.1
- Nitro Version: 2.8.1 

### Describe the bug

The problem arises when utilizing the SDK on a Node.js server environment, where access is restricted to web APIs and not the 'window' object. Consequently, when implementing a server API within Nuxt, the absence of a 'window' object renders certain functionalities ineffective. It appears that the `redirectOrVerifyToken` function was designed with client-side usage in mind. Hence, its inclusion within the `withUserAuthorization` method raises questions. In essence, the issue arises when attempting to use the SDK within a Node server environment.

### Additional context

None

### Logs
```
[nuxt] [request error] [unhandled] [500] window is not defined
  at AuthorizationCodeWithPKCEStrategy.redirectOrVerifyToken (./node_modules/@spotify/web-api-ts-sdk/src/auth/AuthorizationCodeWithPKCEStrategy.ts:51:48)  
  at <anonymous> (./node_modules/@spotify/web-api-ts-sdk/src/auth/AuthorizationCodeWithPKCEStrategy.ts:31:42)  
  at InMemoryCachingStrategy.getOrCreate (./node_modules/@spotify/web-api-ts-sdk/src/caching/GenericCache.ts:31:36)  
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)  
  at AuthorizationCodeWithPKCEStrategy.getOrCreateAccessToken (./node_modules/@spotify/web-api-ts-sdk/src/auth/AuthorizationCodeWithPKCEStrategy.ts:28:23)  
  at SpotifyApi.makeRequest (./node_modules/@spotify/web-api-ts-sdk/src/SpotifyApi.ts:79:33)  
  at PlayerEndpoints.getRequest (./node_modules/@spotify/web-api-ts-sdk/src/endpoints/EndpointsBase.ts:8:16)  
  at Object.handler (./server/api/spotify/status.get.ts:10:1)
  ```

**Comment by athulanilthomas** [comment]
@fostertheweb can you please take a look into this ?

**Comment by fostertheweb** [comment]
You can only use `withAccessToken` on the server when you use the [mixed auth pattern](https://github.com/spotify/spotify-web-api-ts-sdk#mixed-server-and-client-side-authentication)

**Comment by athulanilthomas** [comment]
@fostertheweb In my scenario, there isn't a client, so I need the server to manage the entire authentication process, including redirection.

**Comment by fostertheweb** [comment]
This is a client library, so it does not serve that use case. If you don't want to start from scratch using the Spotify Web API, you could try using [spotify-node-wrapper](https://www.npmjs.com/package/spotify-node-wrapper)

**Comment by athulanilthomas** [comment]
@fostertheweb Thank you for the suggestion. However, currently, the Node.js wrapper only supports the client credentials model for authentication, which doesn't allow access to personal information. I've devised a workaround to make this SDK compatible with server-side operations by customizing the existing _AuthenticateWithPKCE_ strategy. 

For implementation details, please visit: [Endpoint](https://github.com/athulanilthomas/athulanilthomas.github.io/blob/main/server/api/spotify/status.get.ts)
